// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi greeter demo API
This is a greeter demo.

Terms Of Service:

http://www.github.com/elakito/swaggersocket/


    Schemes:
      http
      https
    Host: localhost
    BasePath: /samples/greeter
    Version: 1.0.1
    License: Apache 2.0 http://www.apache.org/licenses/LICENSE-2.0.html

    Consumes:
    - application/json
    - multipart/form-data
    - text/plain

    Produces:
    - application/json

swagger:meta
*/
package restapi
