== Websocket binding for REST

This libary can be used to add the Websocket protocol transparently to the exisitng REST services.
As a result, these services can be invoked as usual using HTTP or using Websocket.

=== Default Binding
This default binding is originated from SwaggerSocket[1] and based on the protocol extension
(org.atmosphere.interceptor.SimpleRestInterceptor) included in Atmosphere 2.4.4[2] to enable arbitrary REST services to be invoked using Websocket.

This binding has the following characteristics.

- Each request contains the method, path, and optional type and data.
- Each request may be sent with a unique-ID for the client to correlate responses to its requests.
- The content-type header can be optionally supplied if the content is present.
- The accept header can be optionally supplied if the response is expected.
- Arbitrary Http headers are supported, but they may be omitted if thet are not part of the application semantics.
- The content entity can be optionally supplied following the envelope.
- A large message can be transported as a series of messages that can be reassembled at the receiving end.
- The server can periodically send a heartbeat message to the connected clients to keep the connections alive.

The following message format is used for this binding. Each message is represented as a text or binary Websocket message.
It consists of the headers part encoded in json and the optional content part which follows the headers part.

[caption="Format: "]
.General Syntax
====
{"id": "*_identifier_*", "code": *_status_code_*, "method": "*_method_*", "path": "*_path_*",
 "type": "*_type_value_*", "accept": "*_accept_value_*", "headers": *_headers_map_*,
 "continue": *_continue_*}
*_content_*
====
where

      - *_identifier_* represents an identifier for the request message which is used in any response message to refer to the original request message,

      - *_status_code_* represents the status code of the response message.

      - *_method_* represents the request method,

      - *_path_* represents the request path,

      - *_type_* and *_accept_* represent the optional content-type and accept header values.

      - *_headers_map_* represents the optional headers other than content-type and accept headers.

      - *_content_* represents the optional content entity.

      - *_continue_* represents the optional boolean value which indicates the message continues, in other words, followed by another message.

===== Message Examples


.A GET request to path /foo
====
{"id": "123", "method": "GET", "path": "/foo"}
====

.A POST request to path /foo with text content "Hello World!"
====
{"id": "124", "method": "POST", "path": "/foo", "type": "text/plain"}Hello World!
====

.A POST request to path /foo with text content "Buenos Dias!" and header "X-Language" set to "es"
====
{"id": "125", "method": "POST", "path": "/foo", "type": "text/plain", "headers": {"X-Language": "es"}}Buenos Dias
====

.A response with content "Hello World!"
====
{"id": "123", "code": 200} +
Hello World!
====

.A response with large content "From a ...... to z" split in two responses
====
{"id": "124", "code": 200, "continue": true}From a ...
====
====
{"id": "124", "code": 200}... to z
====

==== Integration
This websocket binding can be integrated to the server side code that is generated by go-swagger.

===== Server-Side
To enable this websocket binding, add the handler in restapi/conigure_....go.

.Adding the protocol handler at the server-side
----
import (
	...
	"github.com/elakito/swagsock/swagsock"
)

func setupGlobalMiddleware(handler http.Handler) http.Handler {
	return globalMiddleware(handler)
}

// The globalMiddleware uses the swaggersocket handler to handle websocket requests
func globalMiddleware(handler http.Handler) http.Handler {

	// instantiate the protocol handler
	protocolHandler := swagsock.CreateProtocolHandler(nil)

	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		// use the protocol handler to handle websocket requests
		if swagsock.IsWebsocketUpgradeRequested(r) {
			protocolHandler.Serve(handler, w, r)
			return
		}

		// handle normal http requests
		handler.ServeHTTP(w, r)
	})
}
----

A sampel server side code is located at https://github.com/elakito/swagsock/tree/master/examples/greeter


===== Client-Side

The code to enable the client side processing in the generated client code is available, however, this is still in work in progress.

- Integration to the client code requires some changes to go-openapi/runtime. Therefore, currently the demo client includes some locally copied and modified code.
- Currently, the operations are invoked in the same way using runtime.Submit which synchronously waits for the response. To utilize the websocket's asynchronous behavior, it will be more suitable to have the asynchronous version of runtime.Submit. (e.g., adding runtime.SubmitAsync to return the result asynchronously)

A sampel client side code is located at https://github.com/elakito/swagsock/tree/master/examples/greeter-client

==== Samples
 * https://github.com/elakito/swagsock/tree/master/examples/greeter[examples/greeter]
  - This server is generated from examples/greeter/swagger.yaml using go-swagger and it is enabled for websocket. This service has normal request and response operations for greeting service and in addition, the subscribe and unsubscribe operations to subsribe to the greet events and receive the greeting events asynchronously.

 * https://github.com/elakito/swagsock/tree/master/examples/chat[examples/chat]
  - This server is generated from examples/chat/swagger.yaml using go-swagger and it is enabled for websocket. This is a chat service.

 * https://github.com/elakito/swagsock/tree/master/examples/chat-multirooms[examples/chat-multirooms]
  - This server is generated from examples/chat-multirooms/swagger.yaml using go-swagger and it is enabled for websocket. This  is a chat service supporting multiple chat rooms.

 * https://github.com/elakito/swagsock/tree/master/examples/clients/node-client[examples/clients/node-client]
  - A node.js client to call the greeter service.

* https://github.com/elakito/swagsock/tree/master/examples/clients/atmosphere-node-client[examples/clients/atmosphere-node-client]
  - A node.js client based on atmosphere.js to call the greeter service.



==== References

- [1] https://github.com/swagger-api/swagger-socket[]

- [2] https://github.com/Atmosphere/atmosphere[]
