// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/elakito/swagsock/examples/chat/models"
)

// ChatOKCode is the HTTP code returned for type ChatOK
const ChatOKCode int = 200

/*ChatOK A chat acknowledgement

swagger:response chatOK
*/
type ChatOK struct {

	/*
	  In: Body
	*/
	Payload *models.Message `json:"body,omitempty"`
}

// NewChatOK creates ChatOK with default headers values
func NewChatOK() *ChatOK {

	return &ChatOK{}
}

// WithPayload adds the payload to the chat o k response
func (o *ChatOK) WithPayload(payload *models.Message) *ChatOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the chat o k response
func (o *ChatOK) SetPayload(payload *models.Message) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ChatOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
