// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// MembersOKCode is the HTTP code returned for type MembersOK
const MembersOKCode int = 200

/*MembersOK Memebers list

swagger:response membersOK
*/
type MembersOK struct {

	/*
	  In: Body
	*/
	Payload []string `json:"body,omitempty"`
}

// NewMembersOK creates MembersOK with default headers values
func NewMembersOK() *MembersOK {

	return &MembersOK{}
}

// WithPayload adds the payload to the members o k response
func (o *MembersOK) WithPayload(payload []string) *MembersOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the members o k response
func (o *MembersOK) SetPayload(payload []string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *MembersOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]string, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
