==== greeter client

The client side code has been generated from the included https://raw.githubusercontent.com/elakito/swagsock/master/examples/greeter/swagger.yaml[swagger.yaml] of example greeter using the following swagger command.
----
$ swagger generate client -T ../../templates -f ../greeter/swagger.yaml -A greeter-demo

----

The custom template is used to generate the code suitable for the asynchronous nature of swaggersocket in addition to the normal code generated by the default template. More concretely, for each operation `Op`, there will be two client methods, `Op(params *OpParams) (*OpOK, ..., error)` and  `OpAsync(params *OpParams, cb func(string, *OpOK, ..., error), sam AsyncSubmitOption) (string, error)`, where the latter method allows the client to receive the response in the specified callback function. For detail, see https://github.com/elakito/swagsock#client-side[client-side].

===== Run

Make sure the greeter server is started (refer to https://github.com/elakito/swagsock/tree/master/examples/greeter)


To run the http client demo, run
----
$ go run demo_client.go -disable
----

When the `disable` flag is set, the client uses the default http transport.

To run the swaggersocket client demo, run
----
$ go run demo_client.go
----

The swaggersocket client invokes the operations asynchronously either using synchronous `Submit` or asynchronous `SubmitAsync` methods. The operations invoked using `SubmitAsync` are denoted with suffix '_a' in the client's commands. The swaggersocket client supports publish-subscribe operations in addition to the normal request-response operations. In this demo, `subscribe_a` invokes the subscribe operation so that greet messages can be delivered to the client. `unsubscribe_a` invokes the unsubscribe operation to cancel the subscription.

.Console
----
$ go run demo_client.go -disbale
demo_client (swaggersocket false) invoking operations at target http://localhost:8091/samples/greeter ...
Choose user ...
user: foo
foo> help
Available commands
ping                Ping
echo                Echo the message
greet               Greet the person
status              Display the greeting status
summary             Display the greeting summary
help                Display this help message
quit                Quit the application
foo> ping
res*: {"pong":1}
foo> echo hi
res*: {"echo":"hi"}
foo> greet bar hello
res*: {"from":"foo","name":"bar","text":"hello"}
foo> status 
res*: {"count":1,"name":"foo"}
foo> summary
res*: {"greeted":["foo"],"total":1}
foo> 

$ go run demo_client.go -disable
demo_client (swaggersocket false) invoking operations at target http://localhost:8091/samples/greeter ...
Choose user ...
user: bar
bar> ping
res*: {"pong":4}
bar> greet foo how are you?
res*: {"from":"bar","name":"foo","text":"how are you?"}
bar> 


$ go run demo_client.go
demo_client (swaggersocket true) invoking operations at target ws://localhost:8091/samples/greeter ...
Choose user ...
user: foo
foo> help
Available commands
ping                Ping
ping_a              Ping in async-mode
echo                Echo the message
echo_a              Echo the message in async-mode
greet               Greet the person
greet_a             Greet the person in async-mode
status              Display the greeting status
status_a            Display the greeting status in async-mode
summary             Display the greeting summary
summary_a           Display the greeting summary in async-mode
subscribe_a         Subscribe to the greeting events in async-mode
unsubscribe_a       Unsubscribe from the greeting events in async-mode
help                Display this help message
quit                Quit the application
foo> ping
res*: {"pong":5}
foo> ping_a
foo> 
res2: {"pong":6}
foo> echo_a hola
foo> 
res3: {"echo":"hola"}
foo> subscribe_a
foo> 
res4: {}
foo> 
res4: {"from":"bar","name":"foo","text":"hola!"}
foo> greet bar hola!
res*: {"from":"foo","name":"bar","text":"hola!"}
foo> 
res4: {"from":"bar","name":"foo","text":"buenos dias"}
foo> greet * adios

res4: {"from":"foo","name":"*","text":"adios"}
foo> res*: {"from":"foo","name":"*","text":"adios"}
foo> unsubscribe_a 4

res7: {"greeted":["foo","bar"],"total":6}
foo> 

$ go run demo_client.go
demo_client (swaggersocket true) invoking operations at target ws://localhost:8091/samples/greeter ...
Choose user ...
user: bar
bar> ping_a
bar> 
res1: {"pong":7}
bar> subscribe_a
bar> 
res2: {}
bar> greet foo hola!
res*: {"from":"bar","name":"foo","text":"hola!"}
bar> 
res2: {"from":"foo","name":"bar","text":"hola!"}
bar> greet_a foo buenos dias
bar> 
res4: {"from":"bar","name":"foo","text":"buenos dias"}
bar> 
res2: {"from":"foo","name":"*","text":"adios"}
bar> greet_a foo hola
bar> 
res5: {"from":"bar","name":"foo","text":"hola"}
bar> 

----
