// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi swaggersocket chat demo API
This is a swaggersocket chat demo.

Terms Of Service:

http://www.sap.com/vora/terms/


    Schemes:
      http
      https
    Host: localhost
    BasePath: /samples/chat-multirooms
    Version: 1.0.0
    License: Apache 2.0 http://www.apache.org/licenses/LICENSE-2.0.html

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package restapi
