// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetGreetSummaryParams creates a new GetGreetSummaryParams object
// with the default values initialized.
func NewGetGreetSummaryParams() *GetGreetSummaryParams {

	return &GetGreetSummaryParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetGreetSummaryParamsWithTimeout creates a new GetGreetSummaryParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetGreetSummaryParamsWithTimeout(timeout time.Duration) *GetGreetSummaryParams {

	return &GetGreetSummaryParams{

		timeout: timeout,
	}
}

// NewGetGreetSummaryParamsWithContext creates a new GetGreetSummaryParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetGreetSummaryParamsWithContext(ctx context.Context) *GetGreetSummaryParams {

	return &GetGreetSummaryParams{

		Context: ctx,
	}
}

// NewGetGreetSummaryParamsWithHTTPClient creates a new GetGreetSummaryParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetGreetSummaryParamsWithHTTPClient(client *http.Client) *GetGreetSummaryParams {

	return &GetGreetSummaryParams{
		HTTPClient: client,
	}
}

/*GetGreetSummaryParams contains all the parameters to send to the API endpoint
for the get greet summary operation typically these are written to a http.Request
*/
type GetGreetSummaryParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get greet summary params
func (o *GetGreetSummaryParams) WithTimeout(timeout time.Duration) *GetGreetSummaryParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get greet summary params
func (o *GetGreetSummaryParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get greet summary params
func (o *GetGreetSummaryParams) WithContext(ctx context.Context) *GetGreetSummaryParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get greet summary params
func (o *GetGreetSummaryParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get greet summary params
func (o *GetGreetSummaryParams) WithHTTPClient(client *http.Client) *GetGreetSummaryParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get greet summary params
func (o *GetGreetSummaryParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetGreetSummaryParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
