// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/elakito/swagsock/examples/greeter-client/models"
)

// GetGreetSummaryReader is a Reader for the GetGreetSummary structure.
type GetGreetSummaryReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetGreetSummaryReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetGreetSummaryOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetGreetSummaryOK creates a GetGreetSummaryOK with default headers values
func NewGetGreetSummaryOK() *GetGreetSummaryOK {
	return &GetGreetSummaryOK{}
}

/*GetGreetSummaryOK handles this case with default header values.

Greeting summary
*/
type GetGreetSummaryOK struct {
	Payload *models.GreetingSummary
}

func (o *GetGreetSummaryOK) Error() string {
	return fmt.Sprintf("[GET /v1/greet][%d] getGreetSummaryOK  %+v", 200, o.Payload)
}

func (o *GetGreetSummaryOK) GetPayload() *models.GreetingSummary {
	return o.Payload
}

func (o *GetGreetSummaryOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GreetingSummary)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
