// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetGreetStatusParams creates a new GetGreetStatusParams object
// with the default values initialized.
func NewGetGreetStatusParams() *GetGreetStatusParams {
	var ()
	return &GetGreetStatusParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetGreetStatusParamsWithTimeout creates a new GetGreetStatusParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetGreetStatusParamsWithTimeout(timeout time.Duration) *GetGreetStatusParams {
	var ()
	return &GetGreetStatusParams{

		timeout: timeout,
	}
}

// NewGetGreetStatusParamsWithContext creates a new GetGreetStatusParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetGreetStatusParamsWithContext(ctx context.Context) *GetGreetStatusParams {
	var ()
	return &GetGreetStatusParams{

		Context: ctx,
	}
}

// NewGetGreetStatusParamsWithHTTPClient creates a new GetGreetStatusParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetGreetStatusParamsWithHTTPClient(client *http.Client) *GetGreetStatusParams {
	var ()
	return &GetGreetStatusParams{
		HTTPClient: client,
	}
}

/*GetGreetStatusParams contains all the parameters to send to the API endpoint
for the get greet status operation typically these are written to a http.Request
*/
type GetGreetStatusParams struct {

	/*Name
	  greeting name

	*/
	Name string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get greet status params
func (o *GetGreetStatusParams) WithTimeout(timeout time.Duration) *GetGreetStatusParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get greet status params
func (o *GetGreetStatusParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get greet status params
func (o *GetGreetStatusParams) WithContext(ctx context.Context) *GetGreetStatusParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get greet status params
func (o *GetGreetStatusParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get greet status params
func (o *GetGreetStatusParams) WithHTTPClient(client *http.Client) *GetGreetStatusParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get greet status params
func (o *GetGreetStatusParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithName adds the name to the get greet status params
func (o *GetGreetStatusParams) WithName(name string) *GetGreetStatusParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the get greet status params
func (o *GetGreetStatusParams) SetName(name string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *GetGreetStatusParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
