// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/elakito/swagsock/examples/greeter-client/models"
)

// GreetReader is a Reader for the Greet structure.
type GreetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GreetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGreetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGreetOK creates a GreetOK with default headers values
func NewGreetOK() *GreetOK {
	return &GreetOK{}
}

/*GreetOK handles this case with default header values.

A greeting response
*/
type GreetOK struct {
	Payload *models.GreetingReply
}

func (o *GreetOK) Error() string {
	return fmt.Sprintf("[POST /v1/greet/{name}][%d] greetOK  %+v", 200, o.Payload)
}

func (o *GreetOK) GetPayload() *models.GreetingReply {
	return o.Payload
}

func (o *GreetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GreetingReply)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
