// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/elakito/swagsock/swagsock"
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// New creates a new operations API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Client {
	return &Client{transport: transport, formats: formats}
}

/*
Client for operations API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

/*
Echo echos back the message

Echo back the message
*/
func (a *Client) Echo(params *EchoParams) (*EchoOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewEchoParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "echo",
		Method:             "POST",
		PathPattern:        "/v1/echo",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"text/plain"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &EchoReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*EchoOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for echo: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
EchoAsync echos back the message
Limitation: currently only one successful return type is supported
Echo back the message
*/
func (a *Client) EchoAsync(params *EchoParams, cb func(string, *EchoOK, error), sam swagsock.SubmitAsyncOption) (string, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewEchoParams()
	}
	requid, err := a.transport.(swagsock.ClientTransport).SubmitAsync(&runtime.ClientOperation{
		ID:                 "echo",
		Method:             "POST",
		PathPattern:        "/v1/echo",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"text/plain"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &EchoReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}, func(k string, v interface{}) {
		switch value := v.(type) {
		case *EchoOK:
			cb(k, value, nil)
		case error:
			cb(k, nil, value)
		}
	}, sam)
	if err != nil {
		return "", err
	}
	return requid, nil
}

/*
GetGreetStatus shows when the person was greeted last

Show when the person was last greeted
*/
func (a *Client) GetGreetStatus(params *GetGreetStatusParams) (*GetGreetStatusOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetGreetStatusParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "getGreetStatus",
		Method:             "GET",
		PathPattern:        "/v1/greet/{name}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &GetGreetStatusReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetGreetStatusOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for getGreetStatus: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
GetGreetStatusAsync shows when the person was greeted last
Limitation: currently only one successful return type is supported
Show when the person was last greeted
*/
func (a *Client) GetGreetStatusAsync(params *GetGreetStatusParams, cb func(string, *GetGreetStatusOK, error), sam swagsock.SubmitAsyncOption) (string, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetGreetStatusParams()
	}
	requid, err := a.transport.(swagsock.ClientTransport).SubmitAsync(&runtime.ClientOperation{
		ID:                 "getGreetStatus",
		Method:             "GET",
		PathPattern:        "/v1/greet/{name}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &GetGreetStatusReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}, func(k string, v interface{}) {
		switch value := v.(type) {
		case *GetGreetStatusOK:
			cb(k, value, nil)
		case error:
			cb(k, nil, value)
		}
	}, sam)
	if err != nil {
		return "", err
	}
	return requid, nil
}

/*
GetGreetSummary shows who has been greeted

Show who has been greeted
*/
func (a *Client) GetGreetSummary(params *GetGreetSummaryParams) (*GetGreetSummaryOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetGreetSummaryParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "getGreetSummary",
		Method:             "GET",
		PathPattern:        "/v1/greet",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &GetGreetSummaryReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetGreetSummaryOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for getGreetSummary: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
GetGreetSummaryAsync shows who has been greeted
Limitation: currently only one successful return type is supported
Show who has been greeted
*/
func (a *Client) GetGreetSummaryAsync(params *GetGreetSummaryParams, cb func(string, *GetGreetSummaryOK, error), sam swagsock.SubmitAsyncOption) (string, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetGreetSummaryParams()
	}
	requid, err := a.transport.(swagsock.ClientTransport).SubmitAsync(&runtime.ClientOperation{
		ID:                 "getGreetSummary",
		Method:             "GET",
		PathPattern:        "/v1/greet",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &GetGreetSummaryReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}, func(k string, v interface{}) {
		switch value := v.(type) {
		case *GetGreetSummaryOK:
			cb(k, value, nil)
		case error:
			cb(k, nil, value)
		}
	}, sam)
	if err != nil {
		return "", err
	}
	return requid, nil
}

/*
Greet greets someone

Greet someone
*/
func (a *Client) Greet(params *GreetParams) (*GreetOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGreetParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "greet",
		Method:             "POST",
		PathPattern:        "/v1/greet/{name}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &GreetReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GreetOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for greet: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
GreetAsync greets someone
Limitation: currently only one successful return type is supported
Greet someone
*/
func (a *Client) GreetAsync(params *GreetParams, cb func(string, *GreetOK, error), sam swagsock.SubmitAsyncOption) (string, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGreetParams()
	}
	requid, err := a.transport.(swagsock.ClientTransport).SubmitAsync(&runtime.ClientOperation{
		ID:                 "greet",
		Method:             "POST",
		PathPattern:        "/v1/greet/{name}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &GreetReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}, func(k string, v interface{}) {
		switch value := v.(type) {
		case *GreetOK:
			cb(k, value, nil)
		case error:
			cb(k, nil, value)
		}
	}, sam)
	if err != nil {
		return "", err
	}
	return requid, nil
}

/*
Ping pings the greeter service

Ping the greeter service
*/
func (a *Client) Ping(params *PingParams) (*PingOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewPingParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "ping",
		Method:             "GET",
		PathPattern:        "/v1/ping",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &PingReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*PingOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for ping: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
PingAsync pings the greeter service
Limitation: currently only one successful return type is supported
Ping the greeter service
*/
func (a *Client) PingAsync(params *PingParams, cb func(string, *PingOK, error), sam swagsock.SubmitAsyncOption) (string, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewPingParams()
	}
	requid, err := a.transport.(swagsock.ClientTransport).SubmitAsync(&runtime.ClientOperation{
		ID:                 "ping",
		Method:             "GET",
		PathPattern:        "/v1/ping",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &PingReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}, func(k string, v interface{}) {
		switch value := v.(type) {
		case *PingOK:
			cb(k, value, nil)
		case error:
			cb(k, nil, value)
		}
	}, sam)
	if err != nil {
		return "", err
	}
	return requid, nil
}

/*
Subscribe subscribes to the greeting events

Subscribe to the greeteing events
*/
func (a *Client) Subscribe(params *SubscribeParams) (*SubscribeOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewSubscribeParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "subscribe",
		Method:             "GET",
		PathPattern:        "/v1/subscribe/{name}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &SubscribeReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*SubscribeOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for subscribe: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
SubscribeAsync subscribes to the greeting events
Limitation: currently only one successful return type is supported
Subscribe to the greeteing events
*/
func (a *Client) SubscribeAsync(params *SubscribeParams, cb func(string, *SubscribeOK, error), sam swagsock.SubmitAsyncOption) (string, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewSubscribeParams()
	}
	requid, err := a.transport.(swagsock.ClientTransport).SubmitAsync(&runtime.ClientOperation{
		ID:                 "subscribe",
		Method:             "GET",
		PathPattern:        "/v1/subscribe/{name}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &SubscribeReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}, func(k string, v interface{}) {
		switch value := v.(type) {
		case *SubscribeOK:
			cb(k, value, nil)
		case error:
			cb(k, nil, value)
		}
	}, sam)
	if err != nil {
		return "", err
	}
	return requid, nil
}

/*
Unsubscribe unsubscribes from the greeting events

Unsubscribe from the greeting events
*/
func (a *Client) Unsubscribe(params *UnsubscribeParams) (*UnsubscribeOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewUnsubscribeParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "unsubscribe",
		Method:             "DELETE",
		PathPattern:        "/v1/unsubscribe/{sid}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &UnsubscribeReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*UnsubscribeOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for unsubscribe: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
UnsubscribeAsync unsubscribes from the greeting events
Limitation: currently only one successful return type is supported
Unsubscribe from the greeting events
*/
func (a *Client) UnsubscribeAsync(params *UnsubscribeParams, cb func(string, *UnsubscribeOK, error), sam swagsock.SubmitAsyncOption) (string, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewUnsubscribeParams()
	}
	requid, err := a.transport.(swagsock.ClientTransport).SubmitAsync(&runtime.ClientOperation{
		ID:                 "unsubscribe",
		Method:             "DELETE",
		PathPattern:        "/v1/unsubscribe/{sid}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &UnsubscribeReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}, func(k string, v interface{}) {
		switch value := v.(type) {
		case *UnsubscribeOK:
			cb(k, value, nil)
		case error:
			cb(k, nil, value)
		}
	}, sam)
	if err != nil {
		return "", err
	}
	return requid, nil
}

/*
Upload uploads a greeting card

Upload a greeting card
*/
func (a *Client) Upload(params *UploadParams) (*UploadOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewUploadParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "upload",
		Method:             "POST",
		PathPattern:        "/v1/greet/{name}/upload",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"multipart/form-data"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &UploadReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*UploadOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for upload: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
UploadAsync uploads a greeting card
Limitation: currently only one successful return type is supported
Upload a greeting card
*/
func (a *Client) UploadAsync(params *UploadParams, cb func(string, *UploadOK, error), sam swagsock.SubmitAsyncOption) (string, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewUploadParams()
	}
	requid, err := a.transport.(swagsock.ClientTransport).SubmitAsync(&runtime.ClientOperation{
		ID:                 "upload",
		Method:             "POST",
		PathPattern:        "/v1/greet/{name}/upload",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"multipart/form-data"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &UploadReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}, func(k string, v interface{}) {
		switch value := v.(type) {
		case *UploadOK:
			cb(k, value, nil)
		case error:
			cb(k, nil, value)
		}
	}, sam)
	if err != nil {
		return "", err
	}
	return requid, nil
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
