// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/elakito/swagsock/examples/greeter-client/models"
)

// UploadReader is a Reader for the Upload structure.
type UploadReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UploadReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewUploadOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 500:
		result := NewUploadInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewUploadOK creates a UploadOK with default headers values
func NewUploadOK() *UploadOK {
	return &UploadOK{}
}

/*UploadOK handles this case with default header values.

Upload status
*/
type UploadOK struct {
	Payload *models.UploadStatus
}

func (o *UploadOK) Error() string {
	return fmt.Sprintf("[POST /v1/greet/{name}/upload][%d] uploadOK  %+v", 200, o.Payload)
}

func (o *UploadOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.UploadStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUploadInternalServerError creates a UploadInternalServerError with default headers values
func NewUploadInternalServerError() *UploadInternalServerError {
	return &UploadInternalServerError{}
}

/*UploadInternalServerError handles this case with default header values.

Storage Full
*/
type UploadInternalServerError struct {
	Payload string
}

func (o *UploadInternalServerError) Error() string {
	return fmt.Sprintf("[POST /v1/greet/{name}/upload][%d] uploadInternalServerError  %+v", 500, o.Payload)
}

func (o *UploadInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
