// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// RoomsHandlerFunc turns a function with the right signature into a rooms handler
type RoomsHandlerFunc func(RoomsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn RoomsHandlerFunc) Handle(params RoomsParams) middleware.Responder {
	return fn(params)
}

// RoomsHandler interface for that can handle valid rooms params
type RoomsHandler interface {
	Handle(RoomsParams) middleware.Responder
}

// NewRooms creates a new http.Handler for the rooms operation
func NewRooms(ctx *middleware.Context, handler RoomsHandler) *Rooms {
	return &Rooms{Context: ctx, Handler: handler}
}

/*Rooms swagger:route GET /v1/rooms rooms

Get the list of chat rooms

Get the list of chat rooms

*/
type Rooms struct {
	Context *middleware.Context
	Handler RoomsHandler
}

func (o *Rooms) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewRoomsParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
