// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// RoomMembersOKCode is the HTTP code returned for type RoomMembersOK
const RoomMembersOKCode int = 200

/*RoomMembersOK Room members list

swagger:response roomMembersOK
*/
type RoomMembersOK struct {

	/*
	  In: Body
	*/
	Payload []string `json:"body,omitempty"`
}

// NewRoomMembersOK creates RoomMembersOK with default headers values
func NewRoomMembersOK() *RoomMembersOK {

	return &RoomMembersOK{}
}

// WithPayload adds the payload to the room members o k response
func (o *RoomMembersOK) WithPayload(payload []string) *RoomMembersOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the room members o k response
func (o *RoomMembersOK) SetPayload(payload []string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *RoomMembersOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]string, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
