// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"

	strfmt "github.com/go-openapi/strfmt"
)

// NewRoomMembersParams creates a new RoomMembersParams object
// no default values defined in spec.
func NewRoomMembersParams() RoomMembersParams {

	return RoomMembersParams{}
}

// RoomMembersParams contains all the bound params for the room members operation
// typically these are obtained from a http.Request
//
// swagger:parameters roomMembers
type RoomMembersParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*room name
	  Required: true
	  In: path
	*/
	Room string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewRoomMembersParams() beforehand.
func (o *RoomMembersParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rRoom, rhkRoom, _ := route.Params.GetOK("room")
	if err := o.bindRoom(rRoom, rhkRoom, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindRoom binds and validates parameter Room from path.
func (o *RoomMembersParams) bindRoom(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	o.Room = raw

	return nil
}
