// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// RoomMembersHandlerFunc turns a function with the right signature into a room members handler
type RoomMembersHandlerFunc func(RoomMembersParams) middleware.Responder

// Handle executing the request and returning a response
func (fn RoomMembersHandlerFunc) Handle(params RoomMembersParams) middleware.Responder {
	return fn(params)
}

// RoomMembersHandler interface for that can handle valid room members params
type RoomMembersHandler interface {
	Handle(RoomMembersParams) middleware.Responder
}

// NewRoomMembers creates a new http.Handler for the room members operation
func NewRoomMembers(ctx *middleware.Context, handler RoomMembersHandler) *RoomMembers {
	return &RoomMembers{Context: ctx, Handler: handler}
}

/*RoomMembers swagger:route GET /v1/rooms/{room} roomMembers

Get the list of chat room members

Get the list of chat room memebers

*/
type RoomMembers struct {
	Context *middleware.Context
	Handler RoomMembersHandler
}

func (o *RoomMembers) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewRoomMembersParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
