// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// RoomsOKCode is the HTTP code returned for type RoomsOK
const RoomsOKCode int = 200

/*RoomsOK Rooms list

swagger:response roomsOK
*/
type RoomsOK struct {

	/*
	  In: Body
	*/
	Payload []string `json:"body,omitempty"`
}

// NewRoomsOK creates RoomsOK with default headers values
func NewRoomsOK() *RoomsOK {

	return &RoomsOK{}
}

// WithPayload adds the payload to the rooms o k response
func (o *RoomsOK) WithPayload(payload []string) *RoomsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the rooms o k response
func (o *RoomsOK) SetPayload(payload []string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *RoomsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]string, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
