// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/elakito/swagsock/examples/chat-multirooms/models"
)

// UnsubscribeOKCode is the HTTP code returned for type UnsubscribeOK
const UnsubscribeOKCode int = 200

/*UnsubscribeOK Chat summary

swagger:response unsubscribeOK
*/
type UnsubscribeOK struct {

	/*
	  In: Body
	*/
	Payload *models.Summary `json:"body,omitempty"`
}

// NewUnsubscribeOK creates UnsubscribeOK with default headers values
func NewUnsubscribeOK() *UnsubscribeOK {

	return &UnsubscribeOK{}
}

// WithPayload adds the payload to the unsubscribe o k response
func (o *UnsubscribeOK) WithPayload(payload *models.Summary) *UnsubscribeOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the unsubscribe o k response
func (o *UnsubscribeOK) SetPayload(payload *models.Summary) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UnsubscribeOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
