// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetGreetSummaryHandlerFunc turns a function with the right signature into a get greet summary handler
type GetGreetSummaryHandlerFunc func(GetGreetSummaryParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetGreetSummaryHandlerFunc) Handle(params GetGreetSummaryParams) middleware.Responder {
	return fn(params)
}

// GetGreetSummaryHandler interface for that can handle valid get greet summary params
type GetGreetSummaryHandler interface {
	Handle(GetGreetSummaryParams) middleware.Responder
}

// NewGetGreetSummary creates a new http.Handler for the get greet summary operation
func NewGetGreetSummary(ctx *middleware.Context, handler GetGreetSummaryHandler) *GetGreetSummary {
	return &GetGreetSummary{Context: ctx, Handler: handler}
}

/*GetGreetSummary swagger:route GET /v1/greet getGreetSummary

Show who has been greeted

Show who has been greeted

*/
type GetGreetSummary struct {
	Context *middleware.Context
	Handler GetGreetSummaryHandler
}

func (o *GetGreetSummary) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetGreetSummaryParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
