// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/elakito/swagsock/examples/greeter/models"
)

// GetGreetSummaryOKCode is the HTTP code returned for type GetGreetSummaryOK
const GetGreetSummaryOKCode int = 200

/*GetGreetSummaryOK Greeting summary

swagger:response getGreetSummaryOK
*/
type GetGreetSummaryOK struct {

	/*
	  In: Body
	*/
	Payload *models.GreetingSummary `json:"body,omitempty"`
}

// NewGetGreetSummaryOK creates GetGreetSummaryOK with default headers values
func NewGetGreetSummaryOK() *GetGreetSummaryOK {

	return &GetGreetSummaryOK{}
}

// WithPayload adds the payload to the get greet summary o k response
func (o *GetGreetSummaryOK) WithPayload(payload *models.GreetingSummary) *GetGreetSummaryOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get greet summary o k response
func (o *GetGreetSummaryOK) SetPayload(payload *models.GreetingSummary) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetGreetSummaryOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
