// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/elakito/swagsock/examples/greeter/models"
)

// GreetOKCode is the HTTP code returned for type GreetOK
const GreetOKCode int = 200

/*GreetOK A greeting response

swagger:response greetOK
*/
type GreetOK struct {

	/*
	  In: Body
	*/
	Payload *models.GreetingReply `json:"body,omitempty"`
}

// NewGreetOK creates GreetOK with default headers values
func NewGreetOK() *GreetOK {

	return &GreetOK{}
}

// WithPayload adds the payload to the greet o k response
func (o *GreetOK) WithPayload(payload *models.GreetingReply) *GreetOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the greet o k response
func (o *GreetOK) SetPayload(payload *models.GreetingReply) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GreetOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
