// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GreetHandlerFunc turns a function with the right signature into a greet handler
type GreetHandlerFunc func(GreetParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GreetHandlerFunc) Handle(params GreetParams) middleware.Responder {
	return fn(params)
}

// GreetHandler interface for that can handle valid greet params
type GreetHandler interface {
	Handle(GreetParams) middleware.Responder
}

// NewGreet creates a new http.Handler for the greet operation
func NewGreet(ctx *middleware.Context, handler GreetHandler) *Greet {
	return &Greet{Context: ctx, Handler: handler}
}

/*Greet swagger:route POST /v1/greet/{name} greet

Greet someone

Greet someone

*/
type Greet struct {
	Context *middleware.Context
	Handler GreetHandler
}

func (o *Greet) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGreetParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
